config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

 resources :products do
   collection do
     get 'fload'
     post 'search'
     get 'calculation'
   end
 end

 root 'products#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
  validates :name, presence: true
  validates :nameid, presence: true, length: { minimum: 3, message: '3文字より短いのダメだよ！！' }
  validates :arrival, presence: true, numericality: true, length: { is: 8, message: 'yyyymmdd　なんだから8文字でしょｗ！！' }
  validates :expiration, presence: true,numericality: true, length: { is: 8, message: 'yyyymmdd　なんだから8文字でしょｗ！！' }
  validates :ordering, presence: true
end

app/models/search/base.rb
class Search::Base
  include ActiveModel::Model
  include ActiveModel::Validations::Callbacks

  def contains(arel_attribute, value)
    arel_attribute.matches("%#{escape_like(value)}%")
  end

  def escape_like(string)
    string.gsub(/[\\%_]/) { |m| "\\#{m}" }
  end

  def value_to_boolean(value)
    ActiveRecord::ConnectionAdapters::Column.value_to_boolean(value)
  end
end

app/models/search/product.rb
class Search::Product < Search::Base
  ATTRIBUTES = %i(
    name
  )
  attr_accessor(*ATTRIBUTES)

  def matches
    t = ::Product.arel_table
    results = ::Product.all
    results = results.where(contains(t[:name], name)) if name.present?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    @products = Product.all.order(created_at: 'desc')
  end

  def new
    @product = Product.new
    @submit = '商品登録'
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to products_path
    else
      render 'new'
    end
  end

  def fload
    @product = Product.new
    @submit = '検索検索♪'
  end

  def search
    flg         = 0
    name        = params[:name]
    ordering    = params[:ordering]
    expiration  = params[:expiration]
    @datas       = Product.all

    if name.present?
      @datas     = Product.where("name like '%" + "#{name}" + "%'")
      flg       = 1
    end

    if ordering == 'true'
      if flg == 0
        @datas     = Product.where.not(ordering: nil)
        flg       = 1
      else
        @datas     = @datas.where.not(ordering: nil)
      end
    end

    if expiration == 'true'
      @today        =  Time.zone.today
      @ago2         =  @today.ago(2.days)
      @stringtoday  =  @today.strftime("%Y%m%d")
      @stringago2   =  @ago2.strftime("%Y%m%d")
      if flg == 0
        @datas      = Product.where("expiration" <= @stringtoday)
        flg         = 1
      else
        @datas      = Product.where(arrival: @stringago2..@stringtoday)
      end
    end

  end

  def calculation
    @now        = Time.zone.today
    @ago7       = @now.ago(7.days)
    @stringnow  = @now.strftime("%Y%m%d")
    @stringago7 = @ago7.strftime("%Y%m%d")
    @datas      = Product.where(arrival: @stringago7..@stringnow)
    @sums       = @datas.group(:name,:nameid).sum(:ordering)
  end


  private
    def product_params
      params.require(:product).permit(:name,:nameid,:ordering,:arrival,:expiration)
    end

    def fload_params
      params.require(:product).permit(:name)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>System</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
    <h1><%= link_to image_tag('logo.jpg' , class: 'logo'), root_path %></h1>
    <ul id="nav">
      <li>☆☆☆☆☆☆☆☆☆</a></li>
      <li><%= link_to '自動算出' , calculation_products_path %></a></li>
      <li><%= link_to '商品検索' , fload_products_path %></li>
      <li><%= link_to '商品登録' , new_product_path %></li>
      <li>めにゅー4</a></li>
      <li>めにゅー5</a></li>
      <li>めにゅー6</a></li>
      <li>めにゅー7</a></li>
    </ul>
    <%= yield %>
    </div>
  </body>
</html>

app/views/products/calculation.html.erb
<h2>1週間の平均実績を算出した結果<h2>

確認用ディスプレイ→　<%= @stringnow.inspect %> <%= @stringnow %></br>
確認用ディスプレイ→　<%= @now.inspect %> </br>
現在日付が取得できなくなってる、なぜ？↑　一回目に使用した日付がそのまま使われてる？</br>
最新の日付を使用する方法は？　毎回現在日付に上書く方法は？

<table class="display search_html_margin" >
  <tr>
    <th>商品名,商品コード</th>
    <th>算出発注数</th>
  </tr>
  <% @sums.each do |key,value| %>
  <tr>
    <td><%= "#{key}" %></td>
    <td><%= value / 7 %></td>
  </tr>
  <% end %>
</table>

app/views/products/fload.html.erb
<h2>商品検索画面</h2>

<%= form_for :product, url: search_products_path do |f| %>
  <p>
    商品名
    <input type="text" name="name">
  </p>

  <p class="search_html_margin" >
    <%= label_tag :expiration, "消費期限間近商品" %>
    <%= check_box_tag :expiration, "true" %>
  </p>

  <p class="search_html_margin" >
    <%= label_tag :ordering, "発注実績あり商品" %>
    <%= check_box_tag :ordering, "true"  %>
  </p>

  <p class="search_html_margin">
    <%= f.submit @submit %>
  </p>
<% end %>

app/views/products/index.html.erb
<h2>初期画面はとりあえずDB確認用一覧表示　重複防止とログイン実装予定<h2>
<table class="display">
  <tr>
    <th>商品名</th>
    <th>商品コード</th>
    <th>発注実績</th>
    <th>入荷日</th>
    <th>消費期限</th>
  </tr>
  <% @products.each do |product| %>
  <tr>
    <td><%= product.name %></td>
    <td><%= product.nameid %></td>
    <td><%= product.ordering %></td>
    <td><%= product.arrival %></td>
    <td><%= product.expiration %></td>
  </tr>
  <% end %>
</table>

app/views/products/new.html.erb
<h2>商品登録画面</h2>

<%= form_for :product, url: products_path do |f| %>
<p>
  商品名
</p>
<p>
  <%= f.text_field :name, placeholder: 'enter name' %>
  <% if @product.errors.messages[:name].any? %>
  <span class="error"><%= @product.errors.messages[:name][0] %></span>
  <% end %>
</p>

<p class="new_html_margin">
  商品ID
<p>
  <%= f.text_field :nameid, placeholder: 'enter nameid' %>
  <% if @product.errors.messages[:nameid].any? %>
  <span class="error"><%= @product.errors.messages[:nameid][0] %></span>
  <% end %>
</p>

<p class="new_html_margin">
  発注数
<p>
  <%= f.text_field :ordering, placeholder: 'enter ordering' %>
  <% if @product.errors.messages[:ordering].any? %>
  <span class="error"><%= @product.errors.messages[:ordering][0] %></span>
  <% end %>
</p>

<p class="new_html_margin">
  入荷日（yyyymmdd形式）
<p>
  <%= f.text_field :arrival, placeholder: 'enter arrival' %>
  <% if @product.errors.messages[:arrival].any? %>
  <span class="error"><%= @product.errors.messages[:arrival][0] %></span>
  <% end %>
</p>

<p class="new_html_margin">
  消費期限（yyyymmdd形式）
<p>
  <%= f.text_field :expiration, placeholder: 'enter expiration' %>
  <% if @product.errors.messages[:expiration].any? %>
  <span class="error"><%= @product.errors.messages[:expiration][0] %></span>
  <% end %>
</p>

<p class="new_html_margin">
  <%= f.submit @submit %>
</p>
<% end %>
<p class="new_html_margin">
  本来であれば、</br>他のシステムから送られてきた情報を自動で登録する流れになり、</br>
  このページ自体必要はないが、他システムから情報が送られてきたと仮定して</br>
  DBに情報が追加されることを確認するための勉強用簡易版。</br>
  商品IDは採番テーブルから自動採番される予定。
</p>

app/views/products/search.html.erb
<h2>商品検索結果画面</h2>

<%= link_to '商品検索へ戻る' , fload_products_path %>

</br>name送信データ確認用ディスプレイ→　<%= @name.inspect %></br>
expiration送信データ確認用ディスプレイ→　<%= @expiration.inspect %></br>
ordering送信データ確認用ディスプレイ→　<%= @ordering.inspect %></br>
flg送信データ確認用ディスプレイ→　<%= @flg.inspect %></br>

<table class="display search_html_margin" >
  <tr>
    <th>商品名</th>
    <th>商品コード</th>
    <th>発注実績</th>
    <th>入荷日</th>
    <th>消費期限</th>
  </tr>
  <% @datas.each do |data| %>
  <tr>
    <td><%= data.name %></td>
    <td><%= data.nameid %></td>
    <td><%= data.ordering %></td>
    <td><%= data.arrival %></td>
    <td><%= data.expiration %></td>
  </tr>
  <% end %>
</table>